### ISSUE TITLE
How to draw figure-3?

### ISSUE THREAD

**Issue by Ruye-aa** [haoyu94/Coarse-to-fine-correspondences#3]
Hi, this is amazing work.
    I am trying to reproduce the results in your paper. But I encountered a problem when trying to draw Figure 3 in the paper. I learned the knowledge of open3D, but I still don't know how to display the two registered point clouds on one map and connect the corresponding points with lines.
    I would like to ask if you can provide the source code of Figure 3, or tell me what method and function I can use to draw the effect of Figure 3.
    As a beginner in the field, I know this question may be simple, but I'd still appreciate to get your help.
    Thanks！
![0](https://user-images.githubusercontent.com/76813112/149945299-0de88890-315c-4f31-aa20-78fcbd1eab8a.png)

**Comment by haoyu94** [comment]
Hi, thanks for your interest! 

For drawing lines with Open3D, you can check the example given here:
![1642763232(1)](https://user-images.githubusercontent.com/67107542/150516822-28a5795f-9524-4f4c-be5b-0126731cf461.png)
More examples about visualization can be found here: http://www.open3d.org/docs/0.7.0/tutorial/Basic/visualization.html.
You can also check the demo (demo.py) of FCGF (https://github.com/chrischoy/FCGF).

**Comment by Ruye-aa** [comment]
Thank you very much for your kind help, it really helps me a lot.
