### ISSUE TITLE
How to get the result of kitti

### ISSUE THREAD

**Issue by ljnaaa** [haoyu94/Coarse-to-fine-correspondences#4]
I've test the parameters in kitti.yaml but found it can't work, then I refer to the parameter used for 3dMatch and successfully run the code,but the result of recall is only 6.1%, what should I do if I want to get a better result in kitti?

**Comment by haoyu94** [comment]
Hi, thanks for your interest. 

As I separately trained 3DMatch and KITTI, I first uploaded the code for 3DMatch for quick re-implementation of the whole model. I will try to add the code and pre-trained weights for KITTI later.

**Comment by haoyu94** [comment]
The kitti part has been updated.
