### ISSUE TITLE
Questions about the understanding of sinkhorn operations

### ISSUE THREAD

**Issue by qsisi** [haoyu94/Coarse-to-fine-correspondences#5]
Hello! Thanks for open-sourcing this amazing work. Here I got a question about the sinkhorn operation utilized in the paper.

I noticed that there are two versions of sinkhorn operations used in the paper. One is the version from SuperGlue, the other is from the RPMNet. The first version is used to process the soft assignment of coarse-level matching, and the second is for the fine-level matching. 

The two implementations actually differs a lot in implementations, the most obvious one is the choice of padding, one is to pad the score matrix with learnable parameters, while the other chooses the fixed zero scalar.

Could you give some hints about the behind reasons for the two sinkhorn choices when you designed the network? Or what is your understanding of these two implementations of the sinkhorn operations above? That would be so helpful.

Thank you very much for your help.

**Comment by haoyu94** [comment]
Hi, as we observed, the implementation from SuperGlue also works better than the one we used on the fine level. It has been updated in GeoTransformer (https://github.com/qinzheng93/GeoTransformer).
