### ISSUE TITLE
Question about the generation of ground truth confidence matrix at coarse scale

### ISSUE THREAD

**Issue by qsisi** [haoyu94/Coarse-to-fine-correspondences#6]
Hello! I have a question about the equation-(4) in the paper which states about the generation of the gt-confidence matrix at coarse scale:
![image](https://user-images.githubusercontent.com/44374058/175878473-bbaea4dd-0dbd-45b4-a306-f66acef0f888.png)
However, during your code implementation:
https://github.com/haoyu94/Coarse-to-fine-correspondences/blob/dd899ab612ffb15d551aaf4490f1db32cde029fd/lib/utils.py#L148-L158
In my understanding, the **r(i',j')** is actually defined as:
![image](https://user-images.githubusercontent.com/44374058/175879227-9bd2fe01-b06b-4b3a-ade5-f31c652c2cdc.png)
Also the final calculation of **W'(i',j')** is defined as the multiplication of **r(i',j')** and **r(i')**, which is different from the equation-(5) in the paper, could you give some hints about it?

Thanks very much for your help.

**Comment by haoyu94** [comment]
Hi, thanks for your interests in our work and sorry for my late reply. The speed of calculating the ratio using the formulation in paper is overly slow. Therefore in practice we use the number of correspondences to estimate that ratio, for accelerating this procedure. We have a different implementation in GeoTransformer(https://github.com/qinzheng93/GeoTransformer), which follows the formulation but using some tricks for acceleration.
