### ISSUE TITLE
How to use multiple GPU

### ISSUE THREAD

**Issue by yangsihai97** [haoyu94/Coarse-to-fine-correspondences#7]
Hello, author!
How can I use multiple GPUs for training here? I tried the conventional method and found that it didn't work

**Comment by haoyu94** [comment]
Hi, 

thanks for your interest in our work. We didn't train CoFiNet using multiple GPUs. You can modify it yourself for DDP training according to https://pytorch.org/docs/stable/notes/ddp.html. 

If you have already tried that and found it didn't work, could you please show the configurations and probably how you did the parallel training?
