### ISSUE TITLE
Question about ransac pose estimation

### ISSUE THREAD

**Issue by Ericgeese** [haoyu94/Coarse-to-fine-correspondences#8]
Hello, I very appreciate your excellent work.
I have some confusion about **ransac_pose_estimation_correspondences** in lib/tester.py when reading your code
I find  _checkers_ in _o3d.registration.registration_ransac_based_on_correspondence_ can speed up code compared with settings without _checkers_ 
I also find _checkers_ is only used in _o3d.registration.registration_ransac_based_on_feature_matching_ in OverlapPredator Code.
I am curious about how this setting works?

**Comment by haoyu94** [comment]
Hi, thanks for your interest.

Tbh I also didn't go deep into the definition of checkers. But I check my code and the code of Predator. Both use the same checkers. Note that our advantage is that our method directly outputs correspondences. But for predatore, you need to do matching in your ransac. So we are in principle faster then Predator regarding the RANSAC procedure.

**Comment by Ericgeese** [comment]
Thanks for your explanation.
